version: "3"
services:
  calculator:
    build:
      context: ..
      dockerfile: ./build/Dockerfile
    container_name: calculator
    ports:
      - "8080:${HTTP_APP_PORT:-8080}"
      - "8081:${GRPC_APP_PORT:-8081}"
    environment:
      HTTP_APP_PORT: ${HTTP_APP_PORT:-8080}
      HTTP_SHUTDOWN_TIMEOUT: ${HTTP_SHUTDOWN_TIMEOUT:-10}
      GRPC_APP_PORT: ${GRPC_APP_PORT:-8081}
      GRPC_APP_TIMEOUT: ${GRPC_APP_TIMEOUT:-3}
      GRPC_SHUTDOWN_TIMEOUT: ${GRPC_SHUTDOWN_TIMEOUT:-5}
      CALCULATOR_WORKERS: ${CALCULATOR_WORKERS}
      LOG_LEVEL: ${LOG_LEVEL:-"PROD"}
    restart: unless-stopped