version: "3"
services:
  calculator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      HTTP_APP_PORT: ${HTTP_APP_PORT:-8080}
      HTTP_SHUTDOWN_TIMEOUT: ${HTTP_SHUTDOWN_TIMEOUT:-10}
      GRPC_APP_PORT: ${GRPC_APP_PORT:-8081}
      GRPC_APP_TIMEOUT: ${GRPC_APP_TIMEOUT:-3}
      GRPC_SHUTDOWN_TIMEOUT: ${GRPC_SHUTDOWN_TIMEOUT:-5}
      LOG_LEVEL: ${LOG_LEVEL:-PROD}
    restart: unless-stopped
